### ISSUE TITLE
Open/Archived state is not saved during navigation: opening an issue under Archived and going back, navigates to Open Issues

### ISSUE THREAD

**Issue by itislu** [42-student-council/website#158]
### My proposal is:
- [ ] After having created a new issue, the tab state should be set to the Open tab.
- [ ] Clicking on Issues in the header when already in the Archived tab should go back to the Open tab.
- [ ] Otherwise, the tab state should be remembered while navigating through the site.

**Comment by leeoocca** [comment]
This is working now, right?

**Comment by itislu** [comment]
No, if you click on an issue in the archive and then the back button, you get to the open issues.

**Comment by leeoocca** [comment]
Uh, that's not my experience:

[archived.webm](https://github.com/user-attachments/assets/12c90d61-11ce-4fa2-9a70-530f1857fe55)

**Comment by itislu** [comment]
Indeed, going back through the browser button works. But not through the big black `Go Back` button 😁

**Comment by leeoocca** [comment]
Ach so! That's what you mean by going back...

I think the current implementation is quite clean, as it writes directly to browser history. Although I've experienced instances where it bugs and doesn't allow you to go back with the browser navigation, it works great.

Implementing additional logic could complicate it quite a lot, having to store the status somewhere else... Or adapt links in the case of the `Go Back` button. I guess that's inevitable if you want to cover all cases.

**Comment by leeoocca** [comment]
I guess a simple and effective solution could be to replace the `Go Back` button with a simple breadcrumb. This would help twice as it could also indicate whether the issue is open or archived, while also linking to the right page. I wouldn't style it as a button, so this would make the whole interface lighter.

---

[Archived issues]()
## #00 Good issue title
Issue description

_3 March 2024_
